[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.flash_mode = qio
board_build.psram = disable
framework = arduino
monitor_speed = 115200
build_flags = 
    
lib_deps = 
    ttlappalainen/NMEA2000-library@^4.22.0
    https://github.com/offspring/NMEA2000_esp32.git
    sparkfun/SparkFun BME280@^2.0.9
